module.exports = {
	locals: {
		title: "SkootPh",
		productSpecs1: [
			{
				id: 1,
				picture: 'images/scooter1-modal.png',
				name: 'Go Board Titan 8 Single',
				price: 'P37,500',
				motor: 800,
				motorUnit: 'w',
				maxSpeed: 50,
				maxRange: 50,
				battery: '48v-15ah',
				batteryType: 'Sinc Power',
				tireSize: '8*3.3"',
				tireType: 'Solid Tire',
			},
			{
				id: 2,
				picture: 'images/scooter1-modal.png',
				name: 'Go Board Titan 8 Dual',
				price: 'P52,500',
				motor: 800,
				motorUnit: 'w x 2',
				maxSpeed: 50,
				maxRange: 60,
				battery: '48v-20ah',
				batteryType: 'Sinc Power',
				tireSize: '8*3.3"',
				tireType: 'Solid Tire',
			},
		],
		productSpecs2: [
			{
				picture: 'images/scooter2-modal.png',
				name: 'Go Board Titan 10 Dual Motor',
				price: 'P70,000',
				motor: 800,
				motorUnit: 'w x 2',
				maxSpeed: 70,
				maxRange: 65,
				battery: '60v-20.8ah',
				batteryType: 'Sinc Power',
				tireSize: '10"',
				tireType: 'Pneumatic Tire',
			},
			{
				picture: 'images/scooter2-modal.png',
				name: 'Go Board Titan 10 Dual Motor',
				info: '(Powered by LG Battery)',
				price: 'P90,000',
				motor: 800,
				motorUnit: 'w x 2',
				maxSpeed: 70,
				maxRange: 90,
				battery: '60v-28ah',
				batteryType: 'LG Battery',
				tireSize: '10"',
				tireType: 'Pneumatic Tire',
			},
			{
				picture: 'images/scooter2-modal.png',
				name: 'Go Board Titan 11 Dual Motor',
				price: 'P98,000',
				motor: 1200,
				motorUnit: 'w x 2',
				maxSpeed: 80,
				maxRange: 80,
				battery: '60v-23.4ah',
				batteryType: 'LG Battery',
				tireSize: '11"',
				tireType: 'Pneumatic Tire',
			},
			{
				picture: 'images/scooter2-modal.png',
				name: 'Go Board Titan 11 Dual Motor',
				info: '(Powered by LG Battery)',
				price: 'P125,000',
				motor: 1200,
				motorUnit: 'w x 2',
				maxSpeed: 80,
				maxRange: 120,
				battery: '60v-35ah',
				batteryType: 'LG Battery',
				tireSize: '11"',
				tireType: 'Pneumatic Tire',
			},
		],
		productSpecs3: [
			{
				picture: 'images/scooter3-modal.png',
				name: 'Skoot 10s+ Single Motor',
				price: 'P42,000',
				motor: 1200,
				motorUnit: 'w',
				maxSpeed: 50,
				maxRange: 70,
				battery: '60v-15.6ah',
				batteryType: 'Sinc Power',
				tireSize: '10"x2.5"',
				tireType: 'Pneumatic Tire',
			},
			{
				picture: 'images/scooter3-modal.png',
				name: 'Skoot 10s+ Dual Motor',
				price: 'P47,500',
				motor: 800,
				motorUnit: 'w x 2',
				maxSpeed: 50,
				maxRange: 80,
				battery: '48v-23.4ah',
				batteryType: 'Sinc Power',
				tireSize: '10"x2.5"',
				tireType: 'Pneumatic Tire',
			},
			{
				picture: 'images/scooter4-modal.png',
				name: 'Kaabo 10s+ Dual Motor',
				price: 'P55,000',
				motor: 1000,
				motorUnit: 'w x 2',
				maxSpeed: 60,
				maxRange: 90,
				battery: '60v-23.4ah',
				batteryType: 'Sinc Power',
				tireSize: '10"x2.5"',
				tireType: 'Pneumatic Tire'
			},
		]
	}
}